# Generated by Django 3.1.4 on 2021-01-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='role',
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
