# Generated by Django 3.1.4 on 2021-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_name', models.CharField(max_length=30, unique=True)),
                ('Category_file', models.CharField(max_length=100)),
            ],
        ),
    ]
