# Generated by Django 3.1.4 on 2021-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Category_name',
            field=models.CharField(default='Scrap', max_length=30),
            preserve_default=False,
        ),
    ]
