# Generated by Django 3.1.4 on 2021-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=10)),
                ('SubCategory_name', models.CharField(max_length=10)),
                ('Base_price', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('Pic1', models.CharField(max_length=50)),
                ('Pic2', models.CharField(max_length=50)),
                ('Pic3', models.CharField(max_length=50)),
                ('Pic4', models.CharField(max_length=50)),
            ],
        ),
    ]
