# Generated by Django 3.1.4 on 2021-02-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210121_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_ID', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Uid', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=30)),
            ],
        ),
    ]
